### ISSUE TITLE
Add JS (jQuery) snippet to pre-fill custom amount value from the URL/querystring

### ISSUE THREAD

**Issue by pderksen** [wpsimplepay/wp-simple-pay-snippet-library#13]
Although you can set a default in the settings, some site owners want to send their different customers to the same payment page but with specific amounts pre-filled.

Possibly use this format: `?amount=45.67` (use decimal, but optional)

Mozilla donate does something similar:
https://donate.mozilla.org/?amount=45.67

Related: #13, #14, #15

**Comment by protorob** [comment]
Did you find the solution for this scenario?
Thanks in advance
