### ISSUE TITLE
custom-custom-amount-field-type does not allow amounts over 999.99

### ISSUE THREAD

**Issue by adamjohnlea** [wpsimplepay/wp-simple-pay-snippet-library#21]
When using the 'custom-amount-field-type' snippet and an amount over 999.99 is entered, the amount disappears when the custom amount field loses focus. I've confirmed the behavior locally.

The following warning is then displayed in the console: The specified value "1,000.00" is not a valid number. The value must match to the following regular expression: -?(\d+|\d+\.\d+|\.\d+)([eE][-+]?\d+)?

[Relevant HS ticket](https://secure.helpscout.net/conversation/1003141482/136680?folderId=2750290)

**Comment by spencerfinnell** [comment]
This would require the autoformatting in the plugin to detect the input type and set the formatting options to keep out thousand separators and possibly change the decimal separator.
