### ISSUE TITLE
lite-add-wp-user-on-success throw stripe error causes undefined user identifier

### ISSUE THREAD

**Issue by mykola-blu** [wpsimplepay/wp-simple-pay-snippet-library#22]
This plugin try to retrieve user that don't exist, yet. Because it send request before transaction was created.

**Comment by spencerfinnell** [comment]
@6LACK-N1NJA Thank you for the report. I have updated the snippet:

https://github.com/wpsimplepay/wp-simple-pay-snippet-library/blob/master/plugins/lite-add-wp-user-on-success.php

Please be sure to review the updated comments about how this functions for Lite.
