### ISSUE TITLE
Custom Button for WPSimplePay

### ISSUE THREAD

**Issue by bramspencer** [wpsimplepay/wp-simple-pay-snippet-library#23]
Could you provide an example of the HTML used to create the custom link or button?

Having trouble getting the button I'm creating to fire the JS code provided.

**Comment by spencerfinnell** [comment]
@bramspencer Are you referring to a custom button that launches an Overlay form?

**Comment by bramspencer** [comment]
Hi @spencerfinnell , yes exactly right! Am I doing something wrong by just creating a <button> attribute and giving it an id or "my_custom_button"> Because it's not working.

**Comment by spencerfinnell** [comment]
An ID that matches the ID you are targeting in the Javascript should be fine. Can you post your full HTML and Javascript?
