### ISSUE TITLE
Custom CSS Class Button for WPSimplePay

### ISSUE THREAD

**Issue by giulianopires** [wpsimplepay/wp-simple-pay-snippet-library#24]
I tried to add a Class CSS to the plugin so that when I click on a button on my website, it points to the Stripe event.
But I'm in trouble. I tried to add the JS code that you made available in the functions file in WordPress but it didn't work. I get an error saying about the $ variable...

**Comment by spencerfinnell** [comment]
Hello @giulianopires, can you please share the full code snippet you are using?

**Comment by giulianopires** [comment]
Thanks for the disposition @spencerfinnell.
I'm using this: [here](https://github.com/wpsimplepay/wp-simple-pay-snippet-library/blob/master/scripts/launch-from-custom-button.js)

**Comment by giulianopires** [comment]
I get this error when using the code: **syntax error, unexpected '$', expecting variable (T_VARIABLE)**

**Comment by spencerfinnell** [comment]
How are you adding the code? If you are adding it to a PHP file you need to output it in the footer of your website with something like:

```php
add_action( 'wp_footer', function() {
?>

<script>
<!-- Custom Javscript here -->
</script>

<?php
} );

**Comment by giulianopires** [comment]
I was adding it to my theme's _functions.php_ file. Or where should I put it?

**Comment by spencerfinnell** [comment]
You can add it to your theme's `functions.php` if you wrap it in the necessary code above. Or add it to a Javascript file that is already being loaded by your theme. Or use a plugin like https://wordpress.org/plugins/custom-css-js/

Please see:

https://docs.wpsimplepay.com/articles/adding-custom-javascript/
https://docs.wpsimplepay.com/articles/adding-custom-functions/

https://wpsimplepay.com/customize-wp-simple-pay

**Comment by giulianopires** [comment]
I can use Google Tag Manager to enter the code?

**Comment by spencerfinnell** [comment]
I would recommend using a more generic plugin like the ones mentioned above. If you need help implementing customizations please reach out via https://wpsimplepay.com/customize-wp-simple-pay/

**Comment by giulianopires** [comment]
Thanks, but nothing worked! I feel frustrated because I just wanted it to go to Stripe's checkout when I clicked the button on my website...
I will look for another solution.
