### ISSUE TITLE
custom amount snippet not work

### ISSUE THREAD

**Issue by mredodos** [wpsimplepay/wp-simple-pay-snippet-library#25]
https://github.com/wpsimplepay/wp-simple-pay-snippet-library/blob/master/plugins/custom-amount.php

that snippet not work at my end.

**Comment by spencerfinnell** [comment]
https://github.com/wpsimplepay/wp-simple-pay-snippet-library/blob/master/plugins/custom-default-amount.php is needed to set the default value for the custom amount field.

**Comment by mredodos** [comment]
ok thx that work.
