### ISSUE TITLE
call does not work

### ISSUE THREAD

**Issue by simplelinestudio** [wpsimplepay/wp-simple-pay-snippet-library#26]
i added the following code to my theme's footer.php:

`( function( $ ) {
	'use strict';

	// Stripe Checkout forms

	$( '#my_custom_button' ).click( function( e ) {
		e.preventDefault();
		$( '#simpay-form-7587' ).find( '.simpay-payment-btn' ).click();
	} );
}( jQuery ) );
`

so afterwards, i created a button in elementor and added in "advanced", "css class" the #my_custom_button, however i can't in any way add a wp simple pay hook to a button on my theme.
what am I doing wrong? the information available is extremely basic and I can’t identify any other way to do it. can you help me @spencerfinnell ?

**Comment by spencerfinnell** [comment]
Hello @simplelinestudio.

If you are adding a CSS Class to a button, such as `my-class`, then your code would look like this:

```js
$( '.my-class' ).click( function( e ) {
	e.preventDefault();
	$( '#simpay-form-7587' ).find( '.simpay-payment-btn' ).click();
} );
```

The default example uses an `ID` of `#my_custom_button`. A `class` begins with `.`
