### ISSUE TITLE
How to retrieve values of hidden fields?

### ISSUE THREAD

**Issue by pkiula** [wpsimplepay/wp-simple-pay-snippet-library#27]
The documentation here is not very helpful: 
https://docs.wpsimplepay.com/articles/what-happens-after-a-payment/

When I create  a hidden field, say, language. 

```
Value:             fr (or en)
Stripe metadata:   language
```

This goes into Stripe. But how do I retrieve these custom values in the Donation Confirmation or Donation Failure pages? Happy to access these via a webhook function in my `functions.php`, but how? What's the name of the variable?

**Comment by spencerfinnell** [comment]
Hello @pkiula -- so sorry this was not answered. You can find an example of how to access the metadata via webhook event data here: https://library.wpcode.com/snippet/joezqwon/
