### ISSUE TITLE
500 error after changing keys.

### ISSUE THREAD

**Issue by OutThisLife** [wpsimplepay/wp-simple-pay-snippet-library#3]
Stripe is throwing:

`Uncaught exception 'Stripe\Error\InvalidRequest' with message 'No such token`

Whenever using the filters, simpay_secret_key and simpay_publishable_key:

![image](https://cloud.githubusercontent.com/assets/770929/22264853/294dce7e-e23f-11e6-8814-ba762f5919f0.png)

Seems like it's conflicting w/ the keys setup in the plugin settings?

**Comment by pderksen** [comment]
@OutThisLife I see you closed this. Are things working for you now?
