### ISSUE TITLE
Redirect URL

### ISSUE THREAD

**Issue by codysnodgrass** [wpsimplepay/wp-simple-pay-snippet-library#5]
In the previous version we were able to directly change the success page URL. I see the file where it has to be done via the functions.php and for each form ID. Is there anyway around this that would allow from the back-end where the button is created that we can set the success page URL? I've got a client website where we need to be able to change per event that they create, but they don't have access the functions.php page or even the know-how to duplicate the code each time to set up the success page URL. It would be much easier if that was just an option as part of creating the button.

**Comment by pderksen** [comment]
@codysnodgrass Right now this is only doable in code. We'll consider adding it as an option if enough customers/users request it though. I'll be looking into it a bit more.

**Comment by nickyoung87** [comment]
@codysnodgrass Hey Just wanted to let you know that in the latest version there is now a form setting for this under the Payment Options tab.

You can see more here: https://docs.wpsimplepay.com/articles/setting-payment-success-failure-pages/

**Comment by codysnodgrass** [comment]
Great! Thanks for adding the option.
