### ISSUE TITLE
Fix JS for firing over Custom Overlay from custom buttons & Beaver Builder pricing tables

### ISSUE THREAD

**Issue by pderksen** [wpsimplepay/wp-simple-pay-snippet-library#7]
Not sure why a jQuery button click isn't working for them.

Maybe the overlays are launched via CSS?

https://github.com/wpsimplepay/WP-Simple-Pay-Snippet-Library/blob/master/javascript/launch-from-custom-button.js

https://github.com/wpsimplepay/WP-Simple-Pay-Snippet-Library/blob/master/javascript/launch-from-beaver-builder-pricing-tables.js

Update https://docs.wpsimplepay.com/articles/stripe-checkout-custom-buttons/ when done.

**Comment by spencerfinnell** [comment]
Partially: https://github.com/wpsimplepay/WP-Simple-Pay-Snippet-Library/pulls

Will add another snippet that doesn't require JS to launch, if you have full control over the HTML.

**Comment by pderksen** [comment]
Closing as this is complete on the above 2 JS files as well as to https://github.com/wpsimplepay/WP-Simple-Pay-Snippet-Library/blob/master/launch-from-custom-button.html
